SET FOREIGN_KEY_CHECKS=0;    
TRUNCATE TABLE birbs.bird; 
TRUNCATE TABLE birbs.la;  
TRUNCATE TABLE birbs.birdwatcher;
TRUNCATE TABLE birbs.anthr_obj_type; 
TRUNCATE TABLE birbs.bird_photo;  
TRUNCATE TABLE birbs.bird_song;    
TRUNCATE TABLE birbs.book;  
TRUNCATE TABLE birbs.lpl;  
TRUNCATE TABLE birbs.lpt;  
TRUNCATE TABLE birbs.meeting_time;  
TRUNCATE TABLE birbs.plant_type;  
TRUNCATE TABLE birbs.pool_type;  
TRUNCATE TABLE birbs.season;
TRUNCATE TABLE birbs.species;  
TRUNCATE TABLE birbs.species_photo;  
TRUNCATE TABLE birbs.species_song;   
TRUNCATE TABLE birbs.season_type;     
SET FOREIGN_KEY_CHECKS=1;